apiVersion: v1
kind: Pod
metadata:
  name: flaskpod
spec:
  containers:
  - name: flaskapp
    image: cloudyrider/flaskapp:latest
    ports:
    - containerPort: 5000
  imagePullSecrets:
  - name: docker-pull-secret